blueprint:
  name: "Clean & Simple Universal Occupancy Lighting for PIR & Radar Sensors"
  description: 
   
   "# Clean & Simple Universal Occupancy Lighting for PIR & Radar Sensors
    
    
    **Version: 1.5** 
    
    
Motion-activated lighting with optional illuminance check, fixed brightness/color temperature, dim before off 
and schedule restriction via helper. 
Area is occupied if at least one sensor detects presence. 
Separate selection for lights to turn on and lights to turn off.  
Perfect for PIR and radar sensors like Aqara FP300 and Eve Motion.
    
    
    Required = *"
    
    
  domain: automation
  input:
    sensors_conditions:
      name: Sensors & Conditions *
      description: Select sensors and conditions for turning lights on
      icon: mdi:radar
      collapsed: true
      input:
        occupancy_sensors:
          name: Occupancy Sensors *
          description: One or more presence/motion sensors. Area is occupied if at
            least one detects presence.
          default: []
          selector:
            entity:
              domain:
              - binary_sensor
              device_class:
              - occupancy
              - motion
              multiple: true
              reorder: false
        illuminance_sensor:
          name: Illuminance Sensor (optional)
          description: Leave empty to ignore ambient light. Lights will then turn
            on regardless of brightness.
          default: []
          selector:
            entity:
              domain:
              - sensor
              device_class:
              - illuminance
              reorder: false
              multiple: false
        illuminance_threshold:
          name: Illuminance Threshold (lux)
          description: Lights turn on only if current illuminance is below this value
          default: 60
          selector:
            number:
              min: 0.0
              max: 1000.0
              unit_of_measurement: lux
              mode: box
              step: 1.0
    lights_appearance:
      name: Lights & Appearance *
      description: Which lights to control and how they should appear when turned
        on
      icon: mdi:lightbulb-group
      collapsed: true
      input:
        lights_turn_on:
          name: Lights to Turn On *
          description: These lights will be turned on when occupancy is detected (and
            dark enough)
          default: []
          selector:
            target:
              entity:
              - domain:
                - light
        lights_turn_off:
          name: Lights to Turn Off *
          description: These lights will be dimmed/turned off when the area becomes
            unoccupied. Can be the same or different.
          default: []
          selector:
            target:
              entity:
              - domain:
                - light
        brightness_pct:
          name: Brightness when Turning On (%)
          description: Fixed brightness for turn-on action
          default: 100
          selector:
            number:
              min: 1.0
              max: 100.0
              unit_of_measurement: '%'
              mode: box
              step: 1.0
        color_temp_kelvin:
          name: Color Temperature when Turning On (Kelvin)
          description: Fixed color temperature (2700 = warm, 6500 = cool)
          default: 2700
          selector:
            number:
              min: 2000.0
              max: 6500.0
              unit_of_measurement: K
              mode: box
              step: 1.0
    off_delay:
      name: Off Delay
      description: Delay before turning off or starting dim phase
      icon: mdi:timer-outline
      collapsed: true
      input:
        off_delay_minutes:
          name: Main Off Delay (minutes)
          description: Time after last detection before dimming or turning off
          default: 5
          selector:
            number:
              min: 0.0
              max: 60.0
              unit_of_measurement: min
              mode: box
              step: 1.0
    schedule_restriction:
      name: Schedule (Optional)
      description: Restrict the automation to specific time periods using a schedule helper
      icon: mdi:calendar-clock
      collapsed: true
      input:
        enable_schedule_restriction:
          name: Enable Schedule Restriction
          description: If enabled, the automation only runs during the active periods of the selected schedule
          default: false
          selector:
            boolean:
        schedule_helper:
          name: Schedule Helper
          description: Select a Schedule helper schedule that defines when the automation may run
          default: []
          selector:
            entity:
              domain: schedule
              multiple: true
              
    dim_advanced:
      name: Dim before Off (Optional)
      description: Optional courteous behavior – dim as warning before final turn-off
      icon: mdi:brightness-4
      collapsed: true
      input:
        enable_dim_before_off:
          name: Enable Dim before Turning Off
          description: If enabled, selected "Lights to Turn Off" will dim first instead
            of turning off immediately
          default: false
          selector:
            boolean: {}
        dim_brightness_pct:
          name: Dim Brightness (%)
          description: Target brightness at the end of the dimming phase
          default: 20
          selector:
            number:
              min: 1.0
              max: 100.0
              unit_of_measurement: '%'
              mode: box
              step: 1.0
        dim_transition_seconds:
          name: Dim Transition Duration (seconds)
          description: How long the gradual dimming should take
          default: 30
          selector:
            number:
              min: 0.0
              max: 300.0
              unit_of_measurement: sec
              mode: box
              step: 1.0
        dim_delay_minutes:
          name: Hold Time at Dim Level (minutes)
          description: Additional time the lights stay at the dimmed brightness before
            finally turning off
          default: 5
          selector:
            number:
              min: 0.0
              max: 30.0
              unit_of_measurement: min
              mode: box
              step: 1.0
  source_url: https://github.com/MajorLazer2142/home-assistant_blueprints/blob/main/Clean_and_Simple_Universal_Occupancy_Lighting_for_PIR_and_Radar_Sensors.yaml
variables:
  sensors: !input occupancy_sensors
  enable_dim: !input enable_dim_before_off
  illuminance_sensor_entity: !input illuminance_sensor
  schedule_enabled: !input enable_schedule_restriction
  schedule_entity: !input schedule_helper
trigger:
- platform: state
  entity_id: !input occupancy_sensors
  to: 'on'
  id: Occupied
- platform: state
  entity_id: !input occupancy_sensors
  to: 'off'
  for:
    minutes: !input off_delay_minutes
  id: Unoccupied
action:
- choose:
  - conditions:
    - condition: trigger
      id: Occupied
    - condition: or
      conditions:
      - condition: template
        value_template: '{{ illuminance_sensor_entity == [] }}'
      - condition: numeric_state
        entity_id: !input illuminance_sensor
        below: !input illuminance_threshold
    - condition: or
      conditions:
        - "{{ not schedule_enabled }}"
        - condition: state
          entity_id: !input schedule_helper
          state: "on"    
    sequence:
    - service: light.turn_on
      target: !input lights_turn_on
      data:
        brightness_pct: !input brightness_pct
        color_temp_kelvin: !input color_temp_kelvin
  - conditions:
    - condition: trigger
      id: Unoccupied
    - condition: template
      value_template: '{{ expand(sensors) | selectattr(''state'', ''eq'', ''off'')
        | list | length == sensors | length }}'
    sequence:
    - if:
      - condition: template
        value_template: '{{ not enable_dim }}'
      then:
      - service: light.turn_off
        target: !input lights_turn_off
      else:
      - service: light.turn_on
        target: !input lights_turn_off
        data:
          brightness_pct: !input dim_brightness_pct
          transition: !input dim_transition_seconds
      - delay:
          seconds: !input dim_transition_seconds
          minutes: !input dim_delay_minutes
      - service: light.turn_off
        target: !input lights_turn_off
  default: []
mode: restart
