blueprint:
  name: Clean & Simple Universal Occupancy Lighting for PIR & Radar Sensors
  description: >-
    Turns on selected lights when occupancy is detected and ambient light is below a threshold.
    Supports fixed brightness and color temperature on turn-on. Turns off lights after a configurable
    delay when unoccupied. Compatible with any PIR or radar sensor providing occupancy or motion
    device class (examples: Aqara FP300, Eve Motion).
  domain: automation
  input:
    occupancy_sensors:
      name: Occupancy Sensors
      description: 'One or more presence/motion sensors (device_class: occupancy or motion, e.g., Aqara FP300 or Eve Motion). The area is considered occupied if at least one sensor detects occupancy.'
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - occupancy
            - motion
          multiple: true
    illuminance_sensor:
      name: Illuminance Sensor
      description: 'Illuminance sensor in lux (often built into one of the sensors)'
      selector:
        entity:
          domain: sensor
          device_class: illuminance
    illuminance_threshold:
      name: Illuminance Threshold (lux)
      description: Lights turn on only if illuminance is below this value.
      default: 60
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: lux
          mode: box
    brightness_pct:
      name: Brightness when Turning On (%)
      description: 'Fixed brightness when turning on (1-100). Default: 100% (full brightness).'
      default: 100
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: '%'
          mode: box
    color_temp_kelvin:
      name: Color Temperature when Turning On (Kelvin)
      description: 'Fixed color temperature when turning on (2700-6500 K). Default: 2700 K (warm white).'
      default: 2700
      selector:
        number:
          min: 2000
          max: 6500
          unit_of_measurement: K
          mode: box
    lights_turn_on:
      name: Lights to Turn On
      description: >-
        Lights (or switches) that turn on when occupancy is detected and it is dark enough.
        Note: To control switchable outlets/plugs instead of lights, change the entity domain
        from 'switch' to 'light' in the automation editor after creating the automation.
      selector:
        target:
          entity:
            domain: light
    lights_turn_off:
      name: Lights to Turn Off
      description: >-
        Lights (or switches) that turn off when the area becomes unoccupied (after delay).
        Note: To control switchable outlets/plugs instead of lights, change the entity domain
        from 'switch' to 'light' in the automation editor after creating the automation.
      selector:
        target:
          entity:
            domain: light
    off_delay_minutes:
      name: Off Delay (minutes)
      description: Delay after the last sensor reports "off" before turning off lights. 0 = immediate.
      default: 5
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: min
          mode: box

trigger:
  - platform: state
    entity_id: !input occupancy_sensors
    to: "on"
    id: Occupied
  - platform: state
    entity_id: !input occupancy_sensors
    to: "off"
    for:
      minutes: !input off_delay_minutes
    id: Unoccupied

condition: []

action:
  - choose:
      - conditions:
          - condition: trigger
            id: Occupied
          - condition: numeric_state
            entity_id: !input illuminance_sensor
            below: !input illuminance_threshold
        sequence:
          - service: light.turn_on
            target: !input lights_turn_on
            data:
              brightness_pct: !input brightness_pct
              color_temp_kelvin: !input color_temp_kelvin
      - conditions:
          - condition: trigger
            id: Unoccupied
        sequence:
          - service: light.turn_off
            target: !input lights_turn_off
    default: []

mode: single
